apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testkube
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: testkube
      sourceRef:
        kind: HelmRepository
        name: kubeshop
        namespace: ${releaseNamespace}
      version: 1.12.16
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  timeout: 5m0s
  releaseName: testkube
  valuesFrom:
    - kind: ConfigMap
      name: testkube-1.12.16-defaults
  targetNamespace: ${releaseNamespace}